// Code generated by go-swagger; DO NOT EDIT.

// Package server Commercetools Tweakwise integration manager
//
//  A service built for managing the Commercetools to Tweakwise integration
//  Schemes:
//    https
//  Host: localhost:8080
//  BasePath: /
//  Version: 1.0.6
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
