// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A service built for managing the Commercetools to Tweakwise integration",
    "title": "Commercetools Tweakwise integration manager",
    "version": "1.0.6"
  },
  "host": "localhost:8080",
  "paths": {
    "/message/gcp/category": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "message",
          "gcp"
        ],
        "summary": "Receives a GCP message for a category update",
        "parameters": [
          {
            "description": "The category message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GcpMessage"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {}
          }
        }
      }
    },
    "/message/gcp/product": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "message",
          "gcp"
        ],
        "summary": "Receives a GCP message for a product update",
        "parameters": [
          {
            "description": "The product message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GcpMessage"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {}
          }
        }
      }
    }
  },
  "definitions": {
    "GcpMessage": {
      "type": "object",
      "required": [
        "message",
        "subscription"
      ],
      "properties": {
        "message": {
          "type": "object",
          "required": [
            "data",
            "message_id",
            "publish_time"
          ],
          "properties": {
            "attributes": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "data": {
              "description": "The base64-encoded message data",
              "type": "string"
            },
            "message_id": {
              "type": "string"
            },
            "publish_time": {
              "type": "string"
            }
          }
        },
        "subscription": {
          "description": "The resource endpoint",
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Messages about commercetools updates to be received",
      "name": "message"
    },
    {
      "description": "Functions specific to a GCP environment",
      "name": "gcp"
    },
    {
      "description": "Functions to administer application",
      "name": "admin"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A service built for managing the Commercetools to Tweakwise integration",
    "title": "Commercetools Tweakwise integration manager",
    "version": "1.0.6"
  },
  "host": "localhost:8080",
  "paths": {
    "/message/gcp/category": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "message",
          "gcp"
        ],
        "summary": "Receives a GCP message for a category update",
        "parameters": [
          {
            "description": "The category message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GcpMessage"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {}
          }
        }
      }
    },
    "/message/gcp/product": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "message",
          "gcp"
        ],
        "summary": "Receives a GCP message for a product update",
        "parameters": [
          {
            "description": "The product message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GcpMessage"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {}
          }
        }
      }
    }
  },
  "definitions": {
    "GcpMessage": {
      "type": "object",
      "required": [
        "message",
        "subscription"
      ],
      "properties": {
        "message": {
          "type": "object",
          "required": [
            "data",
            "message_id",
            "publish_time"
          ],
          "properties": {
            "attributes": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "data": {
              "description": "The base64-encoded message data",
              "type": "string"
            },
            "message_id": {
              "type": "string"
            },
            "publish_time": {
              "type": "string"
            }
          }
        },
        "subscription": {
          "description": "The resource endpoint",
          "type": "string"
        }
      }
    },
    "GcpMessageMessage": {
      "type": "object",
      "required": [
        "data",
        "message_id",
        "publish_time"
      ],
      "properties": {
        "attributes": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "data": {
          "description": "The base64-encoded message data",
          "type": "string"
        },
        "message_id": {
          "type": "string"
        },
        "publish_time": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Messages about commercetools updates to be received",
      "name": "message"
    },
    {
      "description": "Functions specific to a GCP environment",
      "name": "gcp"
    },
    {
      "description": "Functions to administer application",
      "name": "admin"
    }
  ]
}`))
}
