/*
 * Commercetools Tweakwise Integration
 *
 * A service built for managing the Commercetools to Tweakwise integration
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/demeyerthom/commercetools-tweakwise-integration/internal/server"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	configurationApiService := server.NewConfigurationApiService()
	configurationApiController := server.NewConfigurationApiController(configurationApiService)

	manageApiService := server.NewManageApiService()
	manageApiController := server.NewManageApiController(manageApiService)

	router := server.NewRouter(configurationApiController, manageApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
