/*
 * Commercetools Tweakwise Integration
 *
 * A service built for managing the Commercetools to Tweakwise integration
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// ConfigurationApiService is a service that implements the logic for the ConfigurationApiServicer
// This service should implement the business logic for every endpoint for the ConfigurationApi API.
// Include any external packages or services that will be required by this service.
type ConfigurationApiService struct {
}

// NewConfigurationApiService creates a default api service
func NewConfigurationApiService() ConfigurationApiServicer {
	return &ConfigurationApiService{}
}

// ConfigurationGet - Fetch the current configuration
func (s *ConfigurationApiService) ConfigurationGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ConfigurationGet with the required logic for this service method.
	// Add api_configuration_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//FOOBARBAZ
	//TODO: Uncomment the next line to return response Response(200, Configuration{}) or use other options such as http.Ok ...
	//return Response(200, Configuration{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConfigurationGet method not implemented")
}

// ConfigurationPost - Create a new configuration option
func (s *ConfigurationApiService) ConfigurationPost(ctx context.Context, configuration Configuration) (ImplResponse, error) {
	// TODO - update ConfigurationPost with the required logic for this service method.
	// Add api_configuration_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConfigurationPost method not implemented")
}
