/*
 * Commercetools Tweakwise Integration
 *
 * A service built for managing the Commercetools to Tweakwise integration
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// ManageApiService is a service that implements the logic for the ManageApiServicer
// This service should implement the business logic for every endpoint for the ManageApi API.
// Include any external packages or services that will be required by this service.
type ManageApiService struct {
}

// NewManageApiService creates a default api service
func NewManageApiService() ManageApiServicer {
	return &ManageApiService{}
}

// ConnectPost - Connect the application
func (s *ManageApiService) ConnectPost(ctx context.Context) (ImplResponse, error) {
	// TODO - update ConnectPost with the required logic for this service method.
	// Add api_manage_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	//return Response(202, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConnectPost method not implemented")
}

// StartPost - Start the application
func (s *ManageApiService) StartPost(ctx context.Context) (ImplResponse, error) {
	// TODO - update StartPost with the required logic for this service method.
	// Add api_manage_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	//return Response(202, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("StartPost method not implemented")
}

// StopPost - Stop the application
func (s *ManageApiService) StopPost(ctx context.Context) (ImplResponse, error) {
	// TODO - update StopPost with the required logic for this service method.
	// Add api_manage_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	//return Response(202, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("StopPost method not implemented")
}
