/*
 * Commercetools Tweakwise Integration
 *
 * A service built for managing the Commercetools to Tweakwise integration
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// GcpSourceAllOf - Use GCP to listen for events. See https://docs.commercetools.com/api/projects/subscriptions#google-cloud-pubsub-destination for more information
type GcpSourceAllOf struct {

	// The ID of the project that contains the Pub/Sub topic
	ProjectId string `json:"project_id"`

	// Name of the product topic
	ProductTopic string `json:"product_topic"`
}

// AssertGcpSourceAllOfRequired checks if the required fields are not zero-ed
func AssertGcpSourceAllOfRequired(obj GcpSourceAllOf) error {
	elements := map[string]interface{}{
		"project_id":    obj.ProjectId,
		"product_topic": obj.ProductTopic,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGcpSourceAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GcpSourceAllOf (e.g. [][]GcpSourceAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGcpSourceAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGcpSourceAllOf, ok := obj.(GcpSourceAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGcpSourceAllOfRequired(aGcpSourceAllOf)
	})
}
