// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostMessageGcpCategoryCreatedCode is the HTTP code returned for type PostMessageGcpCategoryCreated
const PostMessageGcpCategoryCreatedCode int = 201

/*PostMessageGcpCategoryCreated OK

swagger:response postMessageGcpCategoryCreated
*/
type PostMessageGcpCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostMessageGcpCategoryCreated creates PostMessageGcpCategoryCreated with default headers values
func NewPostMessageGcpCategoryCreated() *PostMessageGcpCategoryCreated {

	return &PostMessageGcpCategoryCreated{}
}

// WithPayload adds the payload to the post message gcp category created response
func (o *PostMessageGcpCategoryCreated) WithPayload(payload interface{}) *PostMessageGcpCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post message gcp category created response
func (o *PostMessageGcpCategoryCreated) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMessageGcpCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
